### ISSUE TITLE
When will release 0.32 will be ready?

### ISSUE THREAD

**Issue by soninob** [RisingOak/jenkins-client#101]
Do you have any ETA?

**Comment by khmarbaise** [comment]
Based on that you are asking...you have an idea when would be a good time to release ? ;-)

**Comment by soninob** [comment]
today? :-)

**Comment by khmarbaise** [comment]
Ok not really today...but i can see if can make it over the weekend...Ok too ?

**Comment by soninob** [comment]
10x a lot!

**Comment by khmarbaise** [comment]
So done a release in Central. Should be available within a few hours (synch takes some time)...

**Comment by borzamircea** [comment]
Hello! Has this release been tested? Thank you!

**Comment by khmarbaise** [comment]
So release is out...so we can close this.
