### ISSUE TITLE
Cloudbees Folder Support

### ISSUE THREAD

**Issue by terabyte** [RisingOak/jenkins-client#108]
Hey guys,

Just a heads-up, I am working on folder support.  Here is a snapshot of what I have so far:
https://github.com/RisingOak/jenkins-client/commit/213bb62dd2b6cd09b116a9c6f3da4e30ac29bf6b

If you have any advice/feedback about how you'd like it done, feel free to chime in, but don't feel like you need to waste any time on it necessarily until I'm done.  I've examined the code pretty carefully and I think I am making decisions similar to the structure of other things fairly consistently, so hopefully it will be an easy PR to take.

My basic approach so far is adding a FolderJob object, and JenkinsServer.getFolder(Job someJob) which returns a FolderJob object (regardless of job type), on which you can call isFolder() to see if it is a valid folder.  Then, on the FolderJob, you can call getJobs() to get the jobs under it.

I'll also add JenkinsServer.createFolder() and FolderJob.createFolder(), which will probably throw an error if you don't have the cloudbees plugin installed.

The linked history also includes some bugfixes and refactorings.

**Comment by terabyte** [comment]
So, I have a nearly-completed change, but I seem to have broke the integration tests, so it's gonna be Monday probably.

In related news:  nice tests ya got there.  Many thanks.

**Comment by khmarbaise** [comment]
Take your time...and write good tests ;-)

**Comment by terabyte** [comment]
Here is the newest version, I suspect I'm very close to being ready to PR:
https://github.com/RisingOak/jenkins-client/compare/master...terabyte:feature/folder-support

I tried to write an integration test, but I can't figure out how to install the cloudbees plugin in the embedded jenkins instance.  Any help there?  Basically, the "UpdateManager" for that instance can't see any plugins.  I could download a version of the cloudbees HPI plugin file and install it that way, or I could add the live update site and have it download, but I can't figure out how to programmatically do either of those...

**Comment by khmarbaise** [comment]
The problem with the integration tests is a known to me what i don't like...I haven't found a way either yet...

**Comment by terabyte** [comment]
blah...that's bad news =(  For the purposes of this change, should we accept it as-is and make a "todo" to try and write better integration tests later?  Or is there something else I can do shorter-term to make this change more palatable?

**Comment by khmarbaise** [comment]
Merged into 0.3.3.
