### ISSUE TITLE
Need to add jaxen dependency in pom.xml

### ISSUE THREAD

**Issue by yuzhougit** [RisingOak/jenkins-client#111]
@khmarbaise 
Test below code: 
```
           String jobName = "Test";
           String xml = jenkins.getJobXml(jobName);
           JobConfiguration jobConf = new JobConfiguration(xml);
           jobConf.addStringParam("tt", "Test parameter", "1");
```
I found it failed with below exception:
```
java.lang.NoClassDefFoundError: org/jaxen/NamespaceContext
	at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
	at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
	at org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:164)
	...
	... 29 more
```
I found the cause is that no jaxen dependency in pom.xml. 
I guess you guys did not meet it because jenkins-test-harness has an indirect dependency to jaxen. But jenkins-test-harness only be depended in test scope.

**Comment by khmarbaise** [comment]
Many thanks for finding it...and yes you are unfortunately right...

**Comment by khmarbaise** [comment]
Hi yuzhougit, can you please check if this will fix the problem?

**Comment by yuzhougit** [comment]
@khmarbaise , i validated your fix, it works fine. Thanks for your quick response!
