### ISSUE TITLE
Can not get currently running job details from Jenkins server

### ISSUE THREAD

**Issue by gihanmaduranga** [RisingOak/jenkins-client#117]
Hi,
I have created REST service to fetch the job details from Jenkins server.It works fine with already build in jobs.(FAILURE,SUCCESS,ABORTED those status are working fine).I have executed job in Jenkins server and trying to get currently running job status but when i call created rest service it throws an Null point exception when getting jobDetails.getResult().Please refer following link to see my sample code.
http://stackoverflow.com/questions/33686892/how-to-get-jenkins-list-of-job-details-using-jenkins-client-in-java
Please let me know that how can i get job details including current execution jobs status as well.
Thanks.

**Comment by khmarbaise** [comment]
Do you have the full stack trace....

**Comment by gihanmaduranga** [comment]
[stackTrace.txt](https://github.com/RisingOak/jenkins-client/files/39783/stackTrace.txt)

Hi khmarbaise  thank you for quick response .Please refer attached file to get some useful details.

My REST service works fine with the already build in jobs.But when i trying to get details when some jobs are running its throws me a null point exception.Because i set data into Pojo class.

jJobVO.setStatus(jobDetails.getResult().toString()); // throws an null point exception.

Thank you.

**Comment by gihanmaduranga** [comment]
Hi,I have something to clarify from you it is not relevant to this issue.Let say when i submit a job into jenkins it put submitted job into a queue and jenkins send us to a response with necessary headers.

Location=https://build.myjenkins.info/queue/item/798/

I can view details using flowing  URL. https://build.myjenkins.info/queue/item/798 /api/xml
That shows xml file with job details.So my requirement is that i want to get job number according to queue item number(798) and necessary details.I would like to know that using your jenkins client API can i get these details?if so how can i get it.

Thanks.

**Comment by khmarbaise** [comment]
Unfortunately i can't access this url..Unknown URL ?

**Comment by khmarbaise** [comment]
Unfortunately no feedback. So i can't help here. So i close the issue.
