### ISSUE TITLE
Is there any API to download file from Job's workspace?

### ISSUE THREAD

**Issue by yuzhougit** [RisingOak/jenkins-client#119]

**Comment by khmarbaise** [comment]
I would assume just `curl http://localhost:10090/job/javaee/ws/pom.xml` would get the pom file from the workspace...

**Comment by yuzhougit** [comment]
@khmarbaise , curl is an external tool to download it. I want to know if any way in jenkins-client could download file by coding

**Comment by pnathan** [comment]
It would be suboptimal to add a HTTP file download to jenkins-client when
excellent automated tools exist elsewhere.

**Comment by yuzhougit** [comment]
@khmarbaise @pnathan I have found a workaround. In JenkinsHttpClient class, there is an method getFile which could be used to download a file. But the client is an private member of JenkinsServer, you have to get the instance by reflect. Can we expose a GET method in JenkinsServer for user to get the client when they need to use it to do some more advanced thine?

**Comment by khmarbaise** [comment]
I thinks there is no reason not to do such a thing in particular if it helps you...to make things easier...
