### ISSUE TITLE
When will release 0.3.3 will be ready?

### ISSUE THREAD

**Issue by lepffm** [RisingOak/jenkins-client#122]
we need features about folder plugin.
do you have any plan for 0.3.3  release or snapshot?
at least I hope to download it from public maven repository like a bintray. thank you for your work.

**Comment by khmarbaise** [comment]
I would like to do a new release within the next days...

**Comment by lepffm** [comment]
Thank you for all of your had works.

**Comment by ojacquemart** [comment]
Is is possible to publish the release to maven central?
