### ISSUE TITLE
Created date of a jenkins job is missing

### ISSUE THREAD

**Issue by naureen-34** [RisingOak/jenkins-client#126]
Hi Guys,

I have a use case where I need to get the timestamp of the creation of the jenkins job. However I don't see any field in JenkinsJob or JobWithDetaisl model. Am I missing something?

**Comment by khmarbaise** [comment]
Hi, unfortunately i don't see any reference for the creation of a job (or to be honest not that i know)...i can see informations about the build time (started etc.) but not for the creation of the job ...If i check the output in the REST api i can figure out an entry which looks like this...

Do you have an information on the Web UI where it is shown something similar like "created ..." ?

**Comment by naureen-34** [comment]
Hi, this plugin is what I also landed up to. And yes it would mean to make this plugin required. I was looking if we have a better way to deal with it. However there I guess there isn't as created data has not yet been included in core.
