### ISSUE TITLE
Dependency to org.jvnet.hudson:xstream:1.4.7-jenkins-1

### ISSUE THREAD

**Issue by Juchar** [RisingOak/jenkins-client#130]
This artifact is not present in maven central as far as I can see. By consequence an additional repository has to be added just for this single dependency.

Maybe there is an alternative that is in maven central?

**Comment by khmarbaise** [comment]
I've checked and the dependency is only really needed for testing so i have changed the scope to **test**  and it will only being needed for running the tests but not for usual using. I needed to change a a single class which contained a reference to XStream which i have removed.
