### ISSUE TITLE
Unauthorized exception

### ISSUE THREAD

**Issue by iversoncl** [RisingOak/jenkins-client#132]
amazing project！
But when i try to login by username/password,jenkins returns a unauthorized exception.
if login without username/password,i can pass the authentication,but i can't get my job info without my account.
how to solve it?tks

**Comment by soninob** [comment]
@iversoncl - please try to use a token instead of a password (although password also working).
It will help if you can supply the way you are doing the connection

**Comment by iversoncl** [comment]
@soninob   genius! i try it and login success.tks very much!
