### ISSUE TITLE
Problem in Create New Job

### ISSUE THREAD

**Issue by DharmendraPrajapati** [RisingOak/jenkins-client#137]
Hi @khmarbaise ,

Thanks for this API.

I am new in jenkins and in java as well. So i am facing an issue on creating new job. I am using method "createJob(jonName , jobData)" and here i am not getting what kind or format of the data in need to pass.Can you please share any sample code.

**Comment by brainstead** [comment]
thejobdata should be in xml format.

**Comment by DharmendraPrajapati** [comment]
@brainstead  Thanks

**Comment by csxiaoshang** [comment]
> Hi @khmarbaise ,
> 
> Thanks for this API.
> 
> I am new in jenkins and in java as well. So i am facing an issue on creating new job. I am using method "createJob(jonName , jobData)" and here i am not getting what kind or format of the data in need to pass.Can you please share any sample code.

hi Do you know how to generate jobdata in xml form?
