### ISSUE TITLE
access job configuration?

### ISSUE THREAD

**Issue by Viky-zhang** [RisingOak/jenkins-client#139]
Is there any way to get configuration of one job?

Like:
**Python API** do: https://pypi.python.org/pypi/jenkinsapi
job.get_config()

**Comment by khmarbaise** [comment]
What do you mean in detail? You can of course download the configuration of a single job directly via jenkins itself like http://jenkins/job/JobName/config.xml ?

**Comment by Viky-zhang** [comment]
http://jenkins/job/JobName/config.xml  is good,
but why not integrate it into Java API?

**Comment by brainstead** [comment]
@Viky-zhang  you can use the jenkins-cli /jenkins java api  to get job configs. https://github.com/kellyrob99/Jenkins-api-tour

**Comment by khmarbaise** [comment]
You can access the jenkins config.xml by using the Jenkins client via:
```java
public String getJobXml(String jobName);
```
which will give you back the content of the `config.xml` file.
