### ISSUE TITLE
JobWithDetails.getDownstreamProjects() throws NullPointerException

### ISSUE THREAD

**Issue by pavelbely** [RisingOak/jenkins-client#147]
JobWithDetails.getDownstreamProjects() throws NullPointerException presumably because received JSON does not have downstreamJobs field.

java.lang.NullPointerException\n\tat com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)\n\tat com.google.common.collect.Lists$TransformingSequentialList.<init>(Lists.java:560)\n\tat com.google.common.collect.Lists.transform(Lists.java:543)\n\tat com.offbytwo.jenkins.model.JobWithDetails.getDownstreamProjects(JobWithDetails.java:98)\n\tat

**Comment by pnathan** [comment]
What version of Jenkins are you using? What version of jenkins-client are you using?

**Comment by pavelbely** [comment]
Jenkins ver. 1.639
jenkins-client 0.3.2

**Comment by khmarbaise** [comment]
Can you try with jenkins client 0.3.3 ?

**Comment by pavelbely** [comment]
Hi Karl Heinz,
I tried with 0.3.3 and still got the same exception.
