### ISSUE TITLE
Is there anyway to get all the builds for a given job?

### ISSUE THREAD

**Issue by born2snipe** [RisingOak/jenkins-client#148]
The current project I am working on has 1000+ builds for a given job. Currently when I query for all the builds I am only receiving the last 100 builds. Is there any way I can get them all back?

**Comment by pnathan** [comment]
What version of Jenkins are you using?

**Comment by khmarbaise** [comment]
@pnathan The problem here simply that Jenkins limits usually the number of results independent of the jenkins version. There need to be a supplemental parameter / method which handles this case.

**Comment by pnathan** [comment]
@khmarbaise Ah, understood. This suggests to me some kind of iterator or paging system then, based upon the Jenkins API.

**Comment by khmarbaise** [comment]
@pnathan In general there are two solutions. The first one can be some kind of paginating system yes or let the use decide if wants  to have all information in one call......I think the simplest one is to have the all in one result method but the other one is also valuable...So the first might be lowest hanging fruit ...

**Comment by born2snipe** [comment]
Awesome, thank you sir! 😃
