### ISSUE TITLE
Subsequent method calls cuase an "Invalid use of BasicClientConnManager: connection still allocated."

### ISSUE THREAD

**Issue by RainerW** [RisingOak/jenkins-client#32]
The JenkinsHttpClient implementation does not consume the response entity in all cases.

1. getJob that does not exist -> 404 by jenkins 
2. getJob taht does exists  -> "BasicClientConnManager: connection still allocated." error

cause:
In "JenkinsHttpClient::public <T extends BaseModel> T get(String path, Class<T> cls)" the method is exited with an exception. 

solution:
allways consume the entity / make try finally around complete method  eg :

  try {
          response = client.execute(new HttpGet(api(path)), localContext);
          int status = response.getStatusLine().getStatusCode();
          if (status < 200 || status >= 300) {
              throw new HttpResponseException(status, response.getStatusLine().getReasonPhrase());
          }
          return objectFromResponse(cls, response);
        } finally {
          if(response!=null){
            EntityUtils.consume(response.getEntity());
          }
        }

**Comment by khmarbaise** [comment]
Are you willing to create a PR for this problem?

**Comment by RainerW** [comment]
I'm working on something else, so could take some time. But will try to create one

**Comment by khmarbaise** [comment]
Changed your mind ?

**Comment by gmaslowski** [comment]
I think that this issue has been resolved at the beginning of 2015. JenkinsHttpClient already has consume() on httpclients in all calls.

**Comment by khmarbaise** [comment]
So i will close the issue...if it turns out not than the issue can be reopen...
