### ISSUE TITLE
Don't propagate IOException when GET for /CrumbIssuer fails.

### ISSUE THREAD

**Issue by hamaron** [RisingOak/jenkins-client#38]
post() and post_xml() method in JenkinsHttpClient.java has a bug where we always get IOException when CrumbIssuer is not set up in a Jenkins server.
Specifically, the following code always throws IOException before doing POST.

    Crumb crumb = get("/crumbIssuer", Crumb.class);

#26 resolved the Crumb issue for users who set up CrumbIssuer, but it is not always the case.
To support the other users who have not used the CrumbIssuer, we should modify this.

**Comment by hamaron** [comment]
Rebased the branch, considering the feedback given in #39.
The new PR is #109

**Comment by khmarbaise** [comment]
Has been integrated into release 0.3.3
