### ISSUE TITLE
New version to maven central

### ISSUE THREAD

**Issue by khmarbaise** [RisingOak/jenkins-client#43]
Hi,
i just want to know if you plan to create a new release and distribute it to maven central?

Do you like to continue development ? Cause i'm interested in continuing...
Kind regards
Karl HEinz Marbaise

**Comment by khmarbaise** [comment]
I would say simply. Make a release and continue. If we found problems we will file in issues...don't hesitate to make new released which improves only small things...Please continue your good work....If you like having help please ask...

Kind regards
Karl Heinz Marbaise

**Comment by gmaslowski** [comment]
Then the answer is simple ;).

**Comment by ricardozanini** [comment]
I agree with you guys.

If we let things get bigger it will be more difficult to release a new version after all.

@cosmin, if you need help, please ask. :+1:

**Comment by cosmin** [comment]
I'll push a version to central select as 0.3.0.

**Comment by cosmin** [comment]
Version `0.3.0` should be making its way through the Sonatype tubes and hit Maven Central in the next few hours. Thank you all for the patches in this version. Please keep them coming.
