### ISSUE TITLE
Can't delete jobs in not enabled crumbIssue Jenkins Instances

### ISSUE THREAD

**Issue by estebanwasinger** [RisingOak/jenkins-client#56]
Continuing the problem I reported a few days ago about the _**crumbIssuer**_ https://github.com/RisingOak/jenkins-client/issues/51, I stumbled upon the following:
In case of delete a job, if you don't have enable the crumbIssuer feature in your Jenkins instance you can't delete jobs.
```java   
 public void deleteJob(String jobName) throws IOException {
        client.post("/job/" + encode(jobName) + "/doDelete");
    }
```

```java
public <R extends BaseModel, D> R post(String path, D data, Class<R> cls) throws IOException {
        HttpPost request = new HttpPost(api(path));
        Crumb crumb = get("/crumbIssuer", Crumb.class);
        if (crumb != null) {
            request.addHeader(new BasicHeader(crumb.getCrumbRequestField(), crumb.getCrumb()));
        }
//(the rest of the method)
}
```

**The problem**: **deleteJob()** need to make a **POST** call, this **post()** method before make the concrete HTTP call to delete the job, makes a **GET** call to get the _**crumbIssuer**_, for example in my case that i don't have the **crumbIssuer** enabled, this method explode with a HTTP exception: 

```shell
org.apache.http.client.HttpResponseException: Not Found
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:108)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:165)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:232)
	at com.offbytwo.jenkins.JenkinsServer.deleteJob(JenkinsServer.java:239)
````
By now the only method affected by this **post()** method is **deleteJob()**, just because is the only which is using it, but if more method start to use it, also will been failing. 
The most important thing that i see is the design issue in **post()** method, is not cohesive, making a **GET** call inside of the method in charge of making **POST** is not the best way, we need to decouple the **crumbIssuer** thing of the **post()** method, because is taking more responsibility than they should.

Thanks
Esteban

**Comment by thomaswhitcomb** [comment]
I too need to be able to block the crumbIssuer on both creates and deletes.  I overrode the createJob and used the post_xml with a false flag to create a job.  But I can't work around the deleteJob.
