### ISSUE TITLE
JenkinsServer encode(jobName) does not work and prevent loading of maven modules hanging below the job

### ISSUE THREAD

**Issue by greg-junkietech** [RisingOak/jenkins-client#62]
Assuming MyJob builds a Maven multi-module project with 1 module foo.package:my-module.
The Jenkins plugin for Maven creates a subproject for each submodule, these are accessible over REST API like any other job, the job name looks like "MyJob/foo.package:my-module".

For that kind of job, the encode method is not required, calling jenkinsServer.getJob does even fail because of this encode method for that kind of job.

**Comment by khmarbaise** [comment]
Are you interested in updating the issue and create an PR ?

**Comment by khmarbaise** [comment]
Unfortunately there seemed to be no interest in making a PR so i close the issue.
