### ISSUE TITLE
Create Credentials / Run Arbitrary Groovy

### ISSUE THREAD

**Issue by terabyte** [RisingOak/jenkins-client#72]
Hey all,

I need to be able to create credentials in jenkins programmatically.  Based upon some research, the standard way to do this seems to be a heredoc full of groovy *extreme sadface*

See line 105: https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/credentials.rb

On the bright side, implementing "run me some random groovy" endpoint would probably give us control to do whatever we wanted to in jenkins.  We'd still want typesafe APIs wherever possible, but where not, groovy!

Thoughts?  Any advice if I try to implement this?

**Comment by cosmin** [comment]
An API endpoint to run arbitrary groovy might come in handy, although it will make me sad to have to resort to it.

**Comment by cosmin** [comment]
I'd definitely merge it in however, so please feel free to take a stab at it

**Comment by terabyte** [comment]
Regret-filled blessings!  Achievement unlocked! =)

**Comment by terabyte** [comment]
BTW, this should be closed as #74 completes this request.  Thanks!
