### ISSUE TITLE
Any plan to release 0.3.1?

### ISSUE THREAD

**Issue by gaol** [RisingOak/jenkins-client#78]
Sorry to post here, if there is a forum to discuss it, I am happy to move this topic to :-)

The lase release: 0.3.0 has been released half a year, do you have any plan when to release 0.3.1? Thank you very much! :-)

**Comment by mass** [comment]
I second this. A project I'm working on depends on some of the new functionality. Thank you!

**Comment by eitanshp** [comment]
+1

**Comment by soninob** [comment]
+1 waiting for the new release.

**Comment by borzamircea** [comment]
+1 waiting for latest release

**Comment by AndreeaDora** [comment]
+1 for the new release

**Comment by khmarbaise** [comment]
I would like to prepare a release for next week...Is there something which should be come into the release ?

**Comment by cosmin** [comment]
Can you take a look at the jarjar pull request for guava? I'm not sure if the author ever cleaned it up per my comments. I would like to get that in so that we can keep this working with Stash.

**Comment by khmarbaise** [comment]
So we have a release in a staging repository available:

https://oss.sonatype.org/content/repositories/comoffbytwo-1008

Can someone take a look on it...

**Comment by gaol** [comment]
Great news. 
I tested the 0.3.1 against the staging repository, it works great on my cases(getJob,createJob,updateJob, JobWithDetails.build(), etc).

**Comment by khmarbaise** [comment]
So release is done and within a few hours available from maven central.
